# Generated by Django 6.0.2 on 2026-02-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
