# Generated by Django 6.0.2 on 2026-02-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staff_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='joining_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
